from PyQt6 import QtCore, QtGui, QtWidgets
from core.ui.ui_module import ui_module

class module(ui_module):
    def setupUi(self, MainWindow):
        MainWindow.setMouseTracking(True)
        self.file_settings_view_dropdowns = QtWidgets.QWidget(parent=MainWindow)
        self.file_settings_view_dropdowns.setObjectName("file_settings_view_dropdowns")
        self.tiles_tools_dock = QtWidgets.QDockWidget(parent=self.file_settings_view_dropdowns)
        self.tiles_tools_dock.setEnabled(True)
        self.tiles_tools_dock.setGeometry(QtCore.QRect(0, 24, 250, 1048))
        self.tiles_tools_dock.setMinimumSize(QtCore.QSize(250, 100))
        self.tiles_tools_dock.setObjectName("tiles_tools_dock")
        self.tiles_tools_dock_contents = QtWidgets.QWidget()
        self.tiles_tools_dock_contents.setObjectName("tiles_tools_dock_contents")
        self.placement_items = QtWidgets.QTabWidget(parent=self.tiles_tools_dock_contents)
        self.placement_items.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.placement_items.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.placement_items.setObjectName("placement_items")
        self.Tiles = QtWidgets.QWidget()
        self.Tiles.setObjectName("Tiles")
        self.Tiles_scollarea = QtWidgets.QScrollArea(parent=self.Tiles)
        self.Tiles_scollarea.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.Tiles_scollarea.setWidgetResizable(True)
        self.Tiles_scollarea.setObjectName("Tiles_scollarea")
        self.Tiles_items = QtWidgets.QWidget()
        self.Tiles_items.setGeometry(QtCore.QRect(0, 0, 248, 798))
        self.Tiles_items.setObjectName("Tiles_items")
        self.Tiles_scollarea.setWidget(self.Tiles_items)
        self.placement_items.addTab(self.Tiles, "")
        self.Entities = QtWidgets.QWidget()
        self.Entities.setObjectName("Entities")
        self.Entities_scrollarea = QtWidgets.QScrollArea(parent=self.Entities)
        self.Entities_scrollarea.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.Entities_scrollarea.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Entities_scrollarea.setWidgetResizable(True)
        self.Entities_scrollarea.setObjectName("Entities_scrollarea")
        self.Entities_items = QtWidgets.QWidget()
        self.Entities_items.setGeometry(QtCore.QRect(0, 0, 248, 798))
        self.Entities_items.setObjectName("Entities_items")
        self.Entities_scrollarea.setWidget(self.Entities_items)
        self.placement_items.addTab(self.Entities, "")
        self.Tools_tab = QtWidgets.QScrollArea(parent=self.tiles_tools_dock_contents)
        self.Tools_tab.setGeometry(QtCore.QRect(0, 800, 250, 280))
        self.Tools_tab.setWidgetResizable(True)
        self.Tools_tab.setObjectName("Tools_tab")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 278))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tools_displaytext = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.tools_displaytext.setGeometry(QtCore.QRect(0, 0, 50, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.tools_displaytext.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tools_displaytext.setFont(font)
        self.tools_displaytext.setAcceptDrops(False)
        self.tools_displaytext.setStyleSheet(" border: none;")
        self.tools_displaytext.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tools_displaytext.setLineWidth(0)
        self.tools_displaytext.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.tools_displaytext.setAcceptRichText(True)
        self.tools_displaytext.setCursorWidth(0)
        self.tools_displaytext.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tools_displaytext.setObjectName("tools_displaytext")
        self.Tools_tab.setWidget(self.scrollAreaWidgetContents)
        self.tiles_tools_dock.setWidget(self.tiles_tools_dock_contents)

        self.retranslateUi(MainWindow)
        self.placement_items.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.placement_items.setTabText(self.placement_items.indexOf(self.Tiles), _translate("MainWindow", "Tiles"))
        self.placement_items.setTabText(self.placement_items.indexOf(self.Entities), _translate("MainWindow", "Entities"))
        self.tools_displaytext.setPlaceholderText(_translate("MainWindow", "Tools"))
