# Form implementation generated from reading ui file 'C:\Program Files (x86)\Steam\steamapps\common\mapmaker\KAGMapMakerv2\core\ui\src\menubar.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class menubar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMouseTracking(True)
        self.file_settings_view_dropdowns = QtWidgets.QWidget(parent=MainWindow)
        self.file_settings_view_dropdowns.setObjectName("file_settings_view_dropdowns")
        self.pushButton = QtWidgets.QPushButton(parent=self.file_settings_view_dropdowns)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.file_settings_view_dropdowns)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
