
from PyQt6 import QtCore, QtGui, QtWidgets
from core.ui.ui_module import ui_module

class Ui_MainWindow(ui_module):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMouseTracking(True)
        self.file_settings_view_dropdowns = QtWidgets.QWidget(parent=MainWindow)
        self.file_settings_view_dropdowns.setObjectName("file_settings_view_dropdowns")
        self.File_dropdown = QtWidgets.QComboBox(parent=self.file_settings_view_dropdowns)
        self.File_dropdown.setGeometry(QtCore.QRect(0, 0, 60, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.File_dropdown.setFont(font)
        self.File_dropdown.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.File_dropdown.setStyleSheet("padding: 3px;")
        self.File_dropdown.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.File_dropdown.setCurrentText("")
        self.File_dropdown.setFrame(True)
        self.File_dropdown.setObjectName("File_dropdown")
        self.File_dropdown.addItem("")
        self.File_dropdown.addItem("")
        self.File_dropdown.addItem("")
        self.File_dropdown.addItem("")
        self.File_dropdown.addItem("")
        self.Setttings_dropdown = QtWidgets.QComboBox(parent=self.file_settings_view_dropdowns)
        self.Setttings_dropdown.setGeometry(QtCore.QRect(60, 0, 110, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Setttings_dropdown.setFont(font)
        self.Setttings_dropdown.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Setttings_dropdown.setStyleSheet("padding: 3px;")
        self.Setttings_dropdown.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.Setttings_dropdown.setCurrentText("")
        self.Setttings_dropdown.setFrame(True)
        self.Setttings_dropdown.setObjectName("Setttings_dropdown")
        self.Setttings_dropdown.addItem("")
        self.Setttings_dropdown.addItem("")
        self.Setttings_dropdown.addItem("")
        self.Setttings_dropdown.addItem("")
        self.Setttings_dropdown.addItem("")
        self.View_dropdown = QtWidgets.QComboBox(parent=self.file_settings_view_dropdowns)
        self.View_dropdown.setGeometry(QtCore.QRect(170, 0, 80, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.View_dropdown.setFont(font)
        self.View_dropdown.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.View_dropdown.setStyleSheet("padding: 3px;")
        self.View_dropdown.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.View_dropdown.setCurrentText("")
        self.View_dropdown.setFrame(True)
        self.View_dropdown.setObjectName("View_dropdown")
        self.View_dropdown.addItem("")
        self.View_dropdown.addItem("")
        self.View_dropdown.addItem("")
        self.View_dropdown.addItem("")
        self.View_dropdown.addItem("")
        self.tiles_tools_dock = QtWidgets.QDockWidget(parent=self.file_settings_view_dropdowns)
        self.tiles_tools_dock.setEnabled(True)
        self.tiles_tools_dock.setGeometry(QtCore.QRect(0, 32, 250, 1048))
        self.tiles_tools_dock.setMinimumSize(QtCore.QSize(250, 100))
        self.tiles_tools_dock.setObjectName("tiles_tools_dock")
        self.tiles_tools_dock_contents = QtWidgets.QWidget()
        self.tiles_tools_dock_contents.setObjectName("tiles_tools_dock_contents")
        self.placement_items = QtWidgets.QTabWidget(parent=self.tiles_tools_dock_contents)
        self.placement_items.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.placement_items.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.placement_items.setObjectName("placement_items")
        self.Tiles = QtWidgets.QWidget()
        self.Tiles.setObjectName("Tiles")
        self.Tiles_scollarea = QtWidgets.QScrollArea(parent=self.Tiles)
        self.Tiles_scollarea.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.Tiles_scollarea.setWidgetResizable(True)
        self.Tiles_scollarea.setObjectName("Tiles_scollarea")
        self.Tiles_items = QtWidgets.QWidget()
        self.Tiles_items.setGeometry(QtCore.QRect(0, 0, 248, 798))
        self.Tiles_items.setObjectName("Tiles_items")
        self.Tiles_scollarea.setWidget(self.Tiles_items)
        self.placement_items.addTab(self.Tiles, "")
        self.Entities = QtWidgets.QWidget()
        self.Entities.setObjectName("Entities")
        self.Entities_scrollarea = QtWidgets.QScrollArea(parent=self.Entities)
        self.Entities_scrollarea.setGeometry(QtCore.QRect(0, 0, 250, 800))
        self.Entities_scrollarea.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Entities_scrollarea.setWidgetResizable(True)
        self.Entities_scrollarea.setObjectName("Entities_scrollarea")
        self.Entities_items = QtWidgets.QWidget()
        self.Entities_items.setGeometry(QtCore.QRect(0, 0, 248, 798))
        self.Entities_items.setObjectName("Entities_items")
        self.Entities_scrollarea.setWidget(self.Entities_items)
        self.placement_items.addTab(self.Entities, "")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tiles_tools_dock_contents)
        self.scrollArea.setGeometry(QtCore.QRect(0, 800, 250, 280))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 278))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tools_displaytext = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.tools_displaytext.setGeometry(QtCore.QRect(0, 0, 50, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.tools_displaytext.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tools_displaytext.setFont(font)
        self.tools_displaytext.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tools_displaytext.setLineWidth(0)
        self.tools_displaytext.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tools_displaytext.setObjectName("tools_displaytext")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tiles_tools_dock.setWidget(self.tiles_tools_dock_contents)
        MainWindow.setCentralWidget(self.file_settings_view_dropdowns)
        self.tiles_tools_dock.raise_()

        self.retranslateUi(MainWindow)
        self.placement_items.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.File_dropdown.setPlaceholderText(_translate("MainWindow", "File"))
        self.File_dropdown.setItemText(0, _translate("MainWindow", "New"))
        self.File_dropdown.setItemText(1, _translate("MainWindow", "Save"))
        self.File_dropdown.setItemText(2, _translate("MainWindow", "Save As"))
        self.File_dropdown.setItemText(3, _translate("MainWindow", "Load"))
        self.File_dropdown.setItemText(4, _translate("MainWindow", "Render"))
        self.Setttings_dropdown.setPlaceholderText(_translate("MainWindow", "Settings"))
        self.Setttings_dropdown.setItemText(0, _translate("MainWindow", "New"))
        self.Setttings_dropdown.setItemText(1, _translate("MainWindow", "Save"))
        self.Setttings_dropdown.setItemText(2, _translate("MainWindow", "Save As"))
        self.Setttings_dropdown.setItemText(3, _translate("MainWindow", "Load"))
        self.Setttings_dropdown.setItemText(4, _translate("MainWindow", "Render"))
        self.View_dropdown.setPlaceholderText(_translate("MainWindow", "View"))
        self.View_dropdown.setItemText(0, _translate("MainWindow", "New"))
        self.View_dropdown.setItemText(1, _translate("MainWindow", "Save"))
        self.View_dropdown.setItemText(2, _translate("MainWindow", "Save As"))
        self.View_dropdown.setItemText(3, _translate("MainWindow", "Load"))
        self.View_dropdown.setItemText(4, _translate("MainWindow", "Render"))
        self.placement_items.setTabText(self.placement_items.indexOf(self.Tiles), _translate("MainWindow", "Tiles"))
        self.placement_items.setTabText(self.placement_items.indexOf(self.Entities), _translate("MainWindow", "Entities"))
        self.tools_displaytext.setPlaceholderText(_translate("MainWindow", "Tools"))
